src/chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:room_name>/', views.room, name='room'),
]

src/ranking/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'ranking'
urlpatterns = [
    path('',views.IndexList.as_view(), name='index'),
    path('rankpage/<int:ranking_id>/', views.rankpage, name='rankpage'),
    path('new/', views.new,name='new'),
    #path('preview/', views.preview,name='preview'),
    path('search_results/',views.search_results.as_view(),name='search_results'),
    path('Soaring_ranking/', views.Soaring_ranking.as_view(),name='Soaring_ranking'),
    path('newest_ranking/', views.newest_ranking.as_view(),name='newest_ranking'),

    path('rankpaged/<int:ranking_id>/', views.rankpaged,name='rankpaged'),

    path('user/<int:user_id>/', views.userpage,name='userpage'),
    path('user/user_edit/', views.user_edit,name='user_edit'),
    path('user/user_edit_result/', views.user_edit_result,name='user_edit_result'),
    path('delete_ranking/<int:ranking_id>', views.delete_ranking, name='delete_ranking'),

    path('Created_ranking_user/<int:pk>/', views.Created_ranking_user.as_view(),name='Created_ranking_user'),
    path('Posted_ranking_user/<int:pk>/', views.Posted_ranking_user.as_view(),name='Posted_ranking_user'),

    path('TermsofUse/', views.TermsofUse,name='TermsofUse'),
    path('aboutpage/', views.aboutpage,name='aboutpage'),
    path('ads.txt', TemplateView.as_view(template_name='ranking/ads.txt', content_type='text/plain')),

]

src/webranking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin_v905sjd98/', admin.site.urls),
    path('',include('ranking.urls')),
    path('top/', TemplateView.as_view(template_name='top.html'), name='top'),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('auth/', include('allauth.urls')),
    path('chat/',include('chat.urls')),
    path('social_django/', include('social_django.urls')),

    # 認証ファイルの配置
    # path('.well-known/pki-validation/~.txt', TemplateView.as_view(template_name='ranking/~.txt', content_type='text/plain')),
]

src/ranking/models.py
from django.db import models
from django.conf import settings
from userAccount.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.contrib.auth import get_user_model

class create_ranking(models.Model):
    title = models.CharField("タイトル",blank=False, null=False, max_length=150)
    element =models.CharField("要素",blank=False, null=False,max_length=8)
    description = models.TextField("説明",blank=False, null=False,)
    coment_count= models.IntegerField("コメント数",default=0)
    post_count= models.IntegerField("参加数",default=0)
    ranking_updated_at = models.DateTimeField("更新日",auto_now=True)
    int_or_float = models.BooleanField(verbose_name='小数値を適用',default=True,)
    #int_or_floatは、True時小数です。False時整数で保存されます。
    #使用用途しては、対象のランクページのint_or_floatがTrueなのかFalseなのかで判別します。
    #また、投稿ページでの型を設定しておきます。intなのかfloatなのか。
    up_or_down = models.BooleanField(verbose_name='昇順にする。',default=False,)
    #False時降順とする。
    max_number = models.IntegerField("最大値",default=1000000)
    min_number = models.IntegerField("最小値",default=0)
    Createduser = models.ForeignKey(to=CustomUser, verbose_name='ユーザー',related_name='Createduser', on_delete=models.PROTECT)
    Done_ranking = models.BooleanField(verbose_name='1000到達',default=False)
    #Posttoranking = models.ForeignKey(to=Post_rank, related_name='Posttoranking', on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Post_rank(models.Model):
    Post_name = models.CharField("投稿者",blank=False, null=False, max_length=50)
    Post_element =models.FloatField("要素",blank=False, null=False)
    Post_juni = models.IntegerField("順位",default=0)
    Post_hensati = models.FloatField("偏差値",default=50)
    article = models.ForeignKey(to=create_ranking, related_name='Posts', on_delete=models.CASCADE)
    Posteduser = models.ForeignKey(to=CustomUser, verbose_name='投稿ユーザー',related_name='Posteduser', on_delete=models.PROTECT,blank=True,null=True)
    def __str__(self):
        return str(self.Post_name+" "+str(self.Post_element))

class Post_coment(models.Model):
    Post_coment_name = models.CharField("投稿者",blank=False, null=False, max_length=50)
    Post_coment_text =models.TextField("コメント",blank=False, null=False,max_length=300)
    article = models.ForeignKey(to=create_ranking, related_name='Posts_coment', on_delete=models.CASCADE)
    def __str__(self):
        return self.Post_coment_name

src/ranking/forms.py
from django.forms import ModelForm
from .models import create_ranking,Post_rank,Post_coment

class create_rankingForm(ModelForm):
    class Meta:
        model = create_ranking
        fields = ['title', 'element','description','max_number','min_number','up_or_down','int_or_float']

        # def reverse_max_min(self):
        #     max_n = self.cleaned_data.get('max_number')
        #     min_n = self.cleaned_data.get('min_number')
        #     if max_n<=min_n:
        #         # self.add_error('max_number', '最大値と最小値が矛盾しています。')
        #         raise forms.ValidationError('最大値と最小値が矛盾しています。')
        #     return max_n
    #
    # def clean_NGword(self):
    #     super(create_rankingForm, self).clean()
    #     NG_or_OK_title = self.cleaned_data.get('title')
    #     NG_or_OK_element = self.cleaned_data.get('element')
    #     NG_or_OK_discription = self.cleaned_data.get('description')

        # NG_word_set = set(["殺す","殺害","爆破","死ぬ","自殺","http:","https:"])
        # for NG_word in NG_word_set:
        #     if (NG_word in NG_or_OK_title) or (NG_word in NG_or_OK_element) or (NG_word in NG_or_OK_discription):
        #         raise forms.ValidationError("NGワードが含まれています。")


class Post_rankForm(ModelForm):
    class Meta:
        model = Post_rank
        fields = ['Post_name', 'Post_element']

    def clean_NGword(self):
        super(Post_rankForm, self).clean()
        NG_or_OK_rank_element = self.cleaned_data.get('Post_element')
        NG_or_OK_rank_name = self.cleaned_data.get('Post_name')

        # NG_word_set = set(["殺す","殺害","爆破","死ぬ","自殺","http:","https:"])
        # for NG_word in NG_word_set:
        #     if (NG_word in NG_or_OK_rank_element) or (NG_word in NG_or_OK_rank_name):
        #         raise forms.ValidationError("NGワードが含まれています。")


class Post_comentForm(ModelForm):
    class Meta:
        model = Post_coment
        fields = ['Post_coment_name', 'Post_coment_text']

    # def clean_NGword(self):
    #     super(Post_comentForm, self).clean()
    #     NG_or_OK_coment_element = self.cleaned_data.get('Post_coment_text')
    #     NG_or_OK_coment_name = self.cleaned_data.get('Post_coment_name')
    #
    #     NG_word_set = set(["殺す","殺害","爆破","死ぬ","自殺","http:","https:"])
    #     for NG_word in NG_word_set:
    #         if (NG_word in NG_or_OK_coment_element) or (NG_word in NG_or_OK_coment_name):
    #             raise forms.ValidationError("NGワードが含まれています。")

src/ranking/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import create_ranking,Post_rank,Post_coment
from .forms import create_rankingForm,Post_rankForm,Post_comentForm

from django.db import models
from django.conf import settings
from userAccount.models import CustomUser

from django.db.models import Count
from django.views import generic
from django.utils import timezone

from django.contrib import messages
from django.db.models import Q

from django.db.models import Max, Min

import statistics
import math

import json
from django.utils.safestring import mark_safe
from decimal import Decimal
import random

###########ランキングの並び替え関数U(引数はorderによるオブジェクト)################
def rankduke(a):
    a_string_object=[]#投稿をリストに変換
    number_data=[]
    #数値のみのリスト
    hensati=[]
    #偏差値の入るリスト
    for i in a:
        get_data=list(str(i).split())
        a_string_object.append(get_data)
        number_data.append(float(get_data[1]))

    number_data_mean=statistics.mean(number_data)
    #平均値
    hyohensa=Decimal(statistics.pstdev(number_data))
    #標準偏差
    #偏差値＝(x-平均)/標準偏差*10+50
    ranking_juni=[]##実際の順位が入る配列。
    juni_rank_desicion =0
    for j in range(0,len(a_string_object)-1):
        if hyohensa!=0:
            hyohensa = float(hyohensa)
            hensati.append('{:.1f}'.format((number_data[j]-number_data_mean)/hyohensa*10+50))
        else:
            hensati.append(50.0)
        ranking_juni.append(str(juni_rank_desicion+1))
        if a_string_object[j][1]!=a_string_object[j+1][1]:
            juni_rank_desicion =j+1
    if a_string_object[len(a_string_object)-2][1]!=a_string_object[len(a_string_object)-1][1]:
        juni_rank_desicion =j+1
    ranking_juni.append(str(juni_rank_desicion+1))
    if hyohensa!=0:
        hyohensa = float(hyohensa)
        hensati.append('{:.1f}'.format((number_data[-1]-number_data_mean)/hyohensa*10+50))
    else:
        hensati.append(50.0)

    kaifor=0
    for i in a:
        i.Post_juni=ranking_juni[kaifor]
        i.Post_hensati=hensati[kaifor]
        #データを１つずつ、常に保存する。
        i.save()
        kaifor+=1
    return a
#####################################################

###########逆偏差値################
def up_rankduke(a):
    a_string_object=[]#投稿をリストに変換
    number_data=[]
    #数値のみのリスト
    hensati=[]
    #偏差値の入るリスト
    for i in a:
        get_data=list(str(i).split())
        a_string_object.append(get_data)
        number_data.append(float(get_data[1]))

    number_data_mean=statistics.mean(number_data)
    #平均値
    hyohensa=statistics.pstdev(number_data)
    #標準偏差
    #偏差値＝(x-平均)/標準偏差*10+50
    ranking_juni=[]##実際の順位が入る配列。
    juni_rank_desicion =0
    for j in range(0,len(a_string_object)-1):
        if int(hyohensa)!=0:
            hensati.append('{:.1f}'.format(50-(number_data[j]-number_data_mean)/hyohensa*10))
        else:
            hensati.append(50.0)
        ranking_juni.append(str(juni_rank_desicion+1))
        if a_string_object[j][1]!=a_string_object[j+1][1]:
            juni_rank_desicion =j+1
    if a_string_object[len(a_string_object)-2][1]!=a_string_object[len(a_string_object)-1][1]:
        juni_rank_desicion =j+1
    ranking_juni.append(str(juni_rank_desicion+1))
    if int(hyohensa)!=0:
        hensati.append('{:.1f}'.format(50-(number_data[-1]-number_data_mean)/hyohensa*10))
    else:
        hensati.append(50.0)

    kaifor=0
    for i in a:
        i.Post_juni=ranking_juni[kaifor]
        i.Post_hensati=hensati[kaifor]
        #データを１つずつ、常に保存する。
        i.save()
        kaifor+=1
    return a
#####################################################


class IndexList(generic.ListView):
    model=create_ranking#モデル名_listとしてオブジェクトが与えられる。
    paginate_by = 5
    ordering = ('-post_count','-ranking_updated_at')# Choices are: Posts, Posts_coment, description, element, id, title
    template_name = 'ranking/index.html'#無記述だと、「モデル名」_list.htmlに結ばれる。
    #モデルを複数listviwにすることは不可能なのだろうか？
    #下記の通りでRecommendというキーによって二つ目のモデルを追加することが可能になりました。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ####### ログインユーザーが参加済みランキングかどうか判別 #######
        article_list=set()
        if self.request.user.username:
            article_list = Post_rank.objects.filter(Posteduser=self.request.user).values_list('article', flat=True)
            article_list = set(article_list)#表示するランキングが少ない場合、setにしてもその恩恵がとても少ないので、5以上にはするようにしてください。
        context['article_set'] =  article_list

        ####### 新着ランキング表示 #######
        context['Recommend'] =  create_ranking.objects.all().order_by('-id')[:5]

        ####### ランダムランキング表示 #######

        # max_id = create_ranking.objects.all().aggregate(Max('id'))
        # min_id = create_ranking.objects.all().aggregate(Min('id'))
        # random_page_list = random.sample(range(min_id['id__min'],max_id['id__max']), k=10)
        # context['random2'] = random_page_list
        # context['random'] = create_ranking.objects.filter(Q(pk=random_page_list[0]) | Q(pk=random_page_list[1]) | Q(pk=random_page_list[2]) | Q(pk=random_page_list[3]) | Q(pk=random_page_list[4]))

        random_ranking = create_ranking.objects.all()[:5]
        random_ranking = list(random_ranking)
        random.shuffle(random_ranking)
        context['random'] = random_ranking

        ####### 急上昇ランキング表示 #######
        soar_lists=[]
        soar_lists_five=[]
        for soar_list in list(create_ranking.objects.all().order_by('-id')[:100]):
            soar_lists.append([int(soar_list.post_count),int(soar_list.id)])
        soar_lists.sort(reverse=True)
        from itertools import chain
        # https://qa.codeflow.site/questions/431628/how-to-combine-2-or-more-querysets-in-a-django-view
        # chainによってquerysetの結合ができる。
        # 一般的な結合を実施場合、order_byによる順付けの制限が残って並び替えられてしまう。
        if len(soar_lists)>=5:
            tttt=chain(create_ranking.objects.filter(Q(pk=soar_lists[0][1])),create_ranking.objects.filter(Q(pk=soar_lists[1][1])),create_ranking.objects.filter(Q(pk=soar_lists[2][1])),create_ranking.objects.filter(Q(pk=soar_lists[3][1])),create_ranking.objects.filter(Q(pk=soar_lists[4][1])))
            context['Soar'] =tttt


        return context


def rankpage(request, ranking_id):
    rank = get_object_or_404(create_ranking,id=ranking_id)
    a=rank.Posts.order_by('-Post_element')
    post_coment=rank.Posts_coment.order_by('-id')
    # requestがPOSTつまり、フォームで送信されてこのサイトに到達したとき。


    # 上限スイッチを何かしらの理由で消した時、paged関数によってスイッチするため、rankpageが開けてしまうのを阻止するためにrankpageにも同様のスイッチを付与
    if rank.post_count>=1000 and rank.Done_ranking==False:
        rank.Done_ranking=True
        rank.save()

    if rank.Done_ranking==True:
        return redirect('ranking:rankpaged',ranking_id=ranking_id)

    if request.method == "POST":
        Flag=True
        Pform = Post_rankForm(request.POST)
        Cform = Post_comentForm(request.POST)
        rank = get_object_or_404(create_ranking,id=ranking_id)

    ###Cformが正しいコメントが入力されるかどうかを確認する。
        if Cform.is_valid():#正しいフォームの方を保存する。つまり送られたリクエストが正しい方が保存されることになる
            rank.coment_count += 1#コメントするごとに＋１して保存する。投稿も同様
            rank.save()
            Post_coment.objects.create(Post_coment_name=request.POST["Post_coment_name"],Post_coment_text=request.POST["Post_coment_text"],article=rank)
            return redirect('ranking:rankpage',ranking_id=ranking_id)

    else:
        Pform = Post_rankForm
        Cform = Post_comentForm
        max_number=rank.max_number
        min_number=rank.min_number
        return render(request, 'ranking/rankpage.html', {'rankpage': rank,'form':Pform,'a':a,'post_coment':post_coment,'Cform':Cform,'max_number':max_number,'min_number':min_number,})


################ランキング作成#################


def new(request):

    # 最大＜最小のような矛盾は、入力値を保持してエラーメッセと共に作成ページに戻します。
    # 最大、最小に値がない場合は、デフォルト値を代入しています。

    Contradiction_flag=False
    if request.method == "POST":
        cp = request.POST.copy()
        if cp["max_number"]=="":
            cp["max_number"] = int(1000000)
        if cp["min_number"]=="":
            cp["min_number"] = int(0)
        Contradiction_flag=False
        if int(cp["max_number"]) >= int(cp["min_number"]):
        #Queryで渡されるvalueは基本文字、数字の比較は絶対intつけてください。
        #"543"<"12234"が辞書順となりFalseになっていました。
            Contradiction_flag=True
            jfldksa1 = int(cp["max_number"])
            jfldksa2 = int(cp["min_number"])
        form = create_rankingForm(cp)
        NG_word_set = set(["殺す","殺害","爆破","死ぬ","自殺","http:","https:"])
        t = ""
        if form.is_valid():

            if Contradiction_flag==False:
                t = "※最大値と最小値が矛盾しています。"
                return render(request, 'ranking/new.html', {'form':form,'t':t,'cp':cp,})

            for NG_word in NG_word_set:
                if NG_word in str(cp["title"]) or NG_word in str(cp["element"]) or NG_word in str(cp["description"]):
                    t = "※NGワードが含まれています。"
                    return render(request, 'ranking/new.html', {'form':form,'t':t,'cp':cp,})

            newranking = form.save(commit=False)###ユーザーに紐付け成功
            newranking.Createduser = request.user
            newranking.save()
            return redirect('ranking:index')
    else:
        form = create_rankingForm
        return render(request, 'ranking/new.html', {'form':form})

################ランキング作成#################




################検索機能#################
class search_results(generic.ListView):
    model = create_ranking
    template_name = 'ranking/search_results.html'
    paginate_by = 10
    def get_queryset(self):
        queryset = create_ranking.objects.order_by('-id')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(Q(title__icontains=keyword))
            messages.success(self.request, '「{}」の検索結果'.format(keyword))
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['AAA'] =  self.request.GET.get('csrfmiddlewaretoken')

src/ranking/templates/ranking/userpage.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0"> -->
  {% load static %} <!--これと下記の一文によってjavascriptを活用することが可能になった-->
  <!-- <script src="{% static 'js/juni.js' %}" charset="utf-8"></script> -->
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <script data-ad-client="ca-pub-5444509011914766" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <title>ランキングサイトです。</title>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-104974987-5"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-104974987-5');
  </script>

</head>
<body>


  <!-- header -->
  <div class="header">
    <div class="header_container">
      <h1 class="header-headline">
        <a href="{% url 'ranking:index' %}"><img src="{% static 'img/logo.png' %}" class="header_logo"></a>
      </h1>
      <div class="header_right">
        <div class="header_menu">
            <label for="label1"><div class="header_menuicon"><i class="fas fa-ellipsis-h"></i></div></label>
            <input type="checkbox" id="label1"/>
            <div class="hidden_show">
              <!-- 非表示ここから-->
              <div class="header_menucorner"></div>
              <div class="header_menucorner2"></div>
              <div class="header_menubox">
                <form name="search1" method="GET" action="{% url 'ranking:search_results' %}">{% csrf_token %}
                  <dl class="search1">
                    <dt><input type="text" name="keyword" maxlength="20" required id="id_Post_name" placeholder="ランキング検索"></dt>
                    <dd><button><span></span></button></dd>
                    <!-- <dd><button type="submit" class="sbtn2"><i class="fas fa-search"></i><span></span></button></dd> -->
                  </dl>
                </form>
                <div class="header_menulist"><a href="{% url 'ranking:index' %}"></a>トップページ</div>
                <div class="header_menulist"><a href ="{% url 'ranking:new' %}"></a>ランキング作成</div>
                {% if user.id %}
                <div class="header_menulist hidden"><a href="{% url 'ranking:userpage' user_id=user.id %}"></a>マイページ</div>
                {% else %}
                <div class="header_menulist hidden"><a href="{%url 'account_login'%}?next={{ request.path }}"></a>ログイン</div>
                {% endif %}
                <div class="header_menuborder"></div>
                <div class="header_menulist"><a href="{% url 'ranking:aboutpage' %}"></a>about</div>
                <div class="header_menulist"><a href="{% url 'ranking:TermsofUse' %}"></a>利用規約・プライバシーポリシー</div>
                <div class="header_menuborder"></div>
                {% if user.username %}
                <div class="header_menulist"><a href="{%url 'account_logout'%}"></a>ログアウト</div>
                {% endif %}
              </div>
              <!--ここまで -->
            </div>
        </div>
        {% if not user.username %}
        <!-- ログインボタン -->
        <div class="header_account_logout">
          <div class="header_username">ログイン</div>
          <a href="{%url 'account_login'%}?next={{ request.path }}"></a>
        </div>
        {% else %}
        <!-- アカウントボタン -->
            {% if user.first_name %}
            <!-- ツイッターユーザー -->
            <div class="header_account">
              <!-- <div class="header_userimg"><img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" class="header_userimg"></div> -->
              <div class="header_username">{{user.first_name|truncatechars:20}}</div>
            <a href="{% url 'ranking:userpage' user_id=user.id %}"></a>
            </div>
            {% else %}
            <!-- くだらんきんぐユーザー -->
            <div class="header_account">
              <div class="header_username">{{user.username|truncatechars:20}}</div>
            <a href="{% url 'ranking:userpage' user_id=user.id %}"></a>
            </div>
            {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
<!-- header終わり -->




<div class="main">

  <div class="article_container">

    <!-- 入力済み私的ユーザーの情報 -->
    <div class="userpage_account">
          {% if userinfo.first_name %}
          <!-- <img src="{{ userinfo.socialaccount_set.all.0.get_avatar_url }}" class="userpage_img"> -->
          <div class="userpage_detail">
            <div class="userpage_name">{{userinfo.first_name}}</div>
            <p></p>
            <p class="userpage_introduction">{{userinfo.biography}}</p>
            <p class="userpage_twitter"><i class="fab fa-twitter userpage_linkicon"></i><a href="https://twitter.com/{{userinfo.username}}">@{{userinfo.username}}</a></p>
            <p class="userpage_link"><i class="fas fa-link userpage_linkicon"></i>twitter.com</p>
          {% else %}
          <div class="userpage_detail">
             <div class="userpage_name">{{userinfo.username}}</div>
             <p></p>
             <p class="userpage_introduction">{{userinfo.biography}}</p>
          {% endif %}
        </div>
    </div>
    {% if user.username %}
      {% if user.id == userinfo.pk %}
        {% if not user.first_name %}
        <div class="sbtn3"><a href="{% url 'ranking:user_edit' %}"><i class="fas fa-edit"></i></a><a href="{% url 'account_change_password' %}?next={{ request.path }}">パスワードの変更</a></div>
        {% else %}
        <div class="sbtn3"><a href="{% url 'ranking:user_edit' %}"><i class="fas fa-edit"></i></a></div>
        {% endif %}
      {% endif %}
    {% endif %}
  </div>

  <!--            作成ランキング一覧                -->

  <div class="category">
    {% if not Createdranking %}
    <h2 class="category_title">ランキングを作成したことがありません。</h2>
    </div>
    {% else %}
    <h2 class="category_title">作成したランキング</h2>
  </div>

  <div class="article_container">

    {% for i in Createdranking %}
    <article class="article_link">
      <a href="{% url 'ranking:rankpaged' ranking_id=i.id%}">
        <div class="article_contents" id="test13">
          <h3 class="article_title made">{{i|truncatechars:12}}</h2>
          <!-- <p class="article_note">{{i.description}}</p> -->
          <!-- ディスクリプションを入れると文字が長い場合バグるため削除 -->
          <p class="article_participants">{{i.Posts.count}}人</p>
          {% if i.Createduser.id == user.id %}
          <form method="post" action="{% url 'ranking:delete_ranking' i.id %}">{% csrf_token %}
            <button type="submit" class="sbtn4" onclick='return confirm("本当に削除しますか？");'><i class="fa fa-trash" aria-hidden="true"></i></button>
          </form>
          {% endif %}
        </div>
      </a>
    </article>
    {% endfor %}
    {% if Createdranking|length >= 5 %}
    <!--   要素数のif文　　 -->
    <!-- もっと見る -->
    <div class="article_more">
      <a href="{% url 'ranking:Created_ranking_user' pk=userinfo.pk %}" class="article_more-a">もっとみる</a>
    </div>
    {% endif %}

  </div>
  {% endif %}

<!--            参加ランキング一覧                -->
  <div class="category">
    {% if not Postedranking %}
    <h2 class="category_title">ランキングに参加したことがありません。</h2>
    </div>
    {% else %}
    <h2 class="category_title">参加したランキング</h2>
  </div>

  <div class="article_container">


    {% for i in Postedranking %}
    <article class="article_link">
      <a href="{% url 'ranking:rankpaged' ranking_id=i.article.id%}">
        <div class="article_contents">
          <h3 class="article_title">{{i.article}}</h2>
          <p class="article_participants">順位:{{i.Post_juni}}位</p>
          <p class="article_participants">偏差値:{{i.Post_hensati}}</p>
        </div>
      </a>
    </article>
    {% endfor %}

    {% if Postedranking|length >= 5 %}
    <!--   要素数のif文　　 -->
    <!-- もっと見る -->
    <div class="article_more">
      <a href="{% url 'ranking:Posted_ranking_user' pk=userinfo.pk %}" class="article_more-a">もっとみる</a>
    </div>
    {% endif %}

  </div>
  {% endif %}


</div>
</body>

</html>